repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the most recent version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--check-only", "--diff"]

  - repo: https://github.com/google/pyink
    rev: 24.10.0
    hooks:
      - id: pyink
        name: pyink
        entry: pyink
        language: python
        types: [python]
        args: ["--check", "."]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
 